# 数据源配置
spring:
  aop:
    proxy-target-class: true
    auto: true

  datasource:
    dynamic:
      p6spy: false
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        # 主库数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://118.25.37.36:3306/tumo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: 123
        # 从库数据源
        slave:
          # 从数据源开关/默认关闭
          enabled: true
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://118.25.37.36:3306/tumo_slave?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: 123
#          druid: #这里可以重写默认值
#            initial-size: 5
#            public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKUVA/IL/iON8f63bv2i/pIAK+1sXY228slLkTKrI9axwBMIoPV7+PqdRTv6uqMl3j6nei0EDBWEu/Wp/qOQ/ScCAwEAAQ==
      druid: #以下是全局默认值，可以全局更改
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        # 配置检测连接是否有效
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        webStatFilter:
          enabled: true
        statViewServlet:
          enabled: true
          # 设置白名单，不填则允许所有访问
          allow:
          url-pattern: /monitor/druid/*
        filter:
          stat:
            enabled: true
            # 慢SQL记录
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true

