spring:
  redis:
    database: 0
    host: 118.25.37.36 #r-bp1a1d20ac75f604.redis.rds.aliyuncs.com
    port: 6379
    password: 123 # 密码（默认为空）Xxfq2017
    timeout: 6000  # 连接超时时长（毫秒）

#    jedis:
#      shutdown-timeout: 300ms #关闭超时
#      pool:
#        max-active: 600 #连接池最大连接数（使用负值表示没有限制）
#        max-wait: 1000 #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 300 #连接池中的最大空闲连接
#        min-idle: 0 #连接池中的最小空闲连接


      # Lettuce的连接是基于Netty的，连接实例可以在多个线程间共享，
      # 所以，一个多线程的应用可以使用同一个连接实例，而不用担心并发线程的数量。
      # 当然这个也是可伸缩的设计，一个连接实例不够的情况也可以按需增加连接实例。
      # 通过异步的方式可以让我们更好的利用系统资源，而不用浪费线程等待网络或磁盘I/O。
      # Lettuce 是基于 netty 的，netty 是一个多线程、事件驱动的 I/O 框架，
      # 所以 Lettuce 可以帮助我们充分利用异步的优势
    lettuce:
      shutdown-timeout: 300ms #关闭超时
      pool:
        max-active: 600 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 1000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接